name: harmony
namespace: harmony
image: docker.pkg.github.com/srntqn/harmony/harmony
imagePullPolicy: IfNotPresent
resources:
  limits:
    memory: '128Mi'
    cpu: '200m'
clusterRole: admin
secretName: k8s-api-key
verifyApiSsl: False
apiHost: https://kubernetes.default
