apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: harmony
deploy:
  helm:
    releases:
    - name: harmony
      chartPath: chart
      remote: false
      namespace: harmony
      createNamespace: true
      artifactOverrides:
        image: harmony