apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
  - image: docker.pkg.github.com/srntqn/harmony/harmony
deploy:
  helm:
    releases:
    - name: harmony
      chartPath: chart
      remote: false
      artifactOverrides:
        image: docker.pkg.github.com/srntqn/harmony/harmony