apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-conf
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-conf
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_"  }}
data:
{{ ( tpl (.Files.Glob "files/conf.yaml").AsConfig . )| indent 2 }}