apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_"  }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: CONFIG_LOCATION
          value: '{{ .Values.configLocation }}'
        - name: VERIFY_SSL
          value: '{{ .Values.verifyApiSsl }}'
        - name: K8S_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretName }}
              key: token
        - name: K8S_API_SERVER_HOST
          value: '{{ .Values.apiHost }}'
        - name: LOG_LEVEL
          value: '{{ .Values.logLevel }}'
        - name: PYTHONUNBUFFERED
          value: '1'
        - name: PYTHONWARNINGS
          value: 'ignore:Unverified HTTPS request'
        volumeMounts:
        - name: {{ .Values.name }}-conf
          mountPath: /app/config
          volumes:
        securityContext:
          privileged: true
      volumes:
        - name: {{ .Values.name }}-conf
          configMap:
            name: {{ .Values.name }}-conf
