apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.name }}
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_"  }}
type: kubernetes.io/service-account-token